version: 2

sources:
  - name: nat_source
    database: "{{ env_var('PROJECT_ID') }}"
    schema: "{{ target.schema }}"
    tables:
      - name: eco2mix_national_cons_def
      - name: eco2mix_national_tr

  - name: reg_source
    database: "{{ env_var('PROJECT_ID') }}"
    schema: "{{ target.schema }}"
    tables:
      - name: eco2mix_regional_cons_def
      - name: eco2mix_regional_tr
